[project]
name = "vba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "watchgod>=0.8.2",
    "xlwings[all]>=0.33.15",
]
